// <auto-generated />
using AutoPecas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPecas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110225853_AdicionarCamposEstoque")]
    partial class AdicionarCamposEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoPecas.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Motor"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Freios"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Suspensão"
                        });
                });

            modelBuilder.Entity("AutoPecas.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            EstoqueMinimo = 5,
                            Nome = "Filtro de Óleo",
                            Preco = 25.90m,
                            QuantidadeEstoque = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            EstoqueMinimo = 5,
                            Nome = "Pastilha de Freio",
                            Preco = 120.00m,
                            QuantidadeEstoque = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            EstoqueMinimo = 5,
                            Nome = "Amortecedor Dianteiro",
                            Preco = 340.00m,
                            QuantidadeEstoque = 0
                        });
                });

            modelBuilder.Entity("AutoPecas.Models.Produto", b =>
                {
                    b.HasOne("AutoPecas.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AutoPecas.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
